# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OpenMinedSwiftSyft', :path => '../../swiftsyft-parcel'
  pod 'Alamofire', '~> 5.4'
  pod 'AppAuth', '~> 1.4.0'
  pod 'SwiftCSV', '~> 0.6'

  pod 'shared', :path => '../shared'

end
